---
- hosts: jenkins
  sudo: yes
  vars:
    jenkins_plugins:
      - git
      - ssh

    jenkins_home: /var/lib/jenkins

  pre_tasks:
    - name: Apt | Update cache
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Jenkins | Packages use in construction process
      apt: name={{ item }} state=latest
      with_items:
        - git
        - subversion
        - zip

  roles:
    - { role: geerlingguy.jenkins }
